// Reads plaintext from toBeEncrypted.txt, encrypts it with AES-128 in CTR
// mode and writes the resulting ciphertext (raw bytes) to afterEncryption.txt.

// Tested agains the CTR example vectors from https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38a.pdf (Appendix F: Example Vectors for Modes of Operation of the AES)
// Output vectors generated by the current algorithm match the ones displayed within the document 

// Average encryption time for 100 MB of data: 3 ms (2 ms lowest, 4 ms greatest)

#include <iostream>
#include <fstream>
#include <cstdio>
#include <cstdlib>
#include <cstdint>
#include <vector>
#include <chrono>
#include <thread>       
#include <algorithm>    
#include <string.h>     // used withing aes.c (for memset)
#include <immintrin.h>  // AES-NI + AVX2 intrinsics

// AES C++ style header (wrapper over aes.h)
#include "aes.hpp"

// Including aes.c instead of creating a separate library for it, as its CTR-specific methods
// will end up being modified later for performance purposes.
extern "C" {
#include "aes.c"
}

// Exit statuses
enum EXIT_STATUS : int {
    SUCCESS                       = 0,
    UNABLE_TO_OPEN_INPUT_FILE     = 1,
    UNABLE_TO_GET_INPUT_SIZE      = 2,
    UNABLE_TO_READ_INPUT_CONTENTS = 3,
    UNABLE_TO_OPEN_OUTPUT_FILE    = 4,
    UNABLE_TO_WRITE_TO_OUTPUT     = 5
};

// Thread Count 
static constexpr size_t threadCount = 16;

// Input (unencrypted data) and output (encrypted data) file names
static constexpr char kInputFile[]  = "toBeEncrypted.txt";
static constexpr char kOutputFile[] = "afterEncryption.txt";

// 16-byte (128-bit) key and IV for AES-128 (CTR uses the IV as the initial counter).
static constexpr uint8_t key[AES_KEYLEN]   = { 0x2b, 0x7e, 0x15, 0x16, 0x28, 0xae, 0xd2, 0xa6,
                                               0xab, 0xf7, 0x15, 0x88, 0x09, 0xcf, 0x4f, 0x3c };
static constexpr uint8_t iv[AES_BLOCKLEN]  = { 0xf0, 0xf1, 0xf2, 0xf3, 0xf4, 0xf5, 0xf6, 0xf7,
                                               0xf8, 0xf9, 0xfa, 0xfb, 0xfc, 0xfd, 0xfe, 0xff };

//  Custom AES-128 CTR keystream consisting of:
//  - AES-NI 
//  - 8-block pipelining 
//  - std::thread 
//  - AVX2 intrinsics
//  Inspired by the scalar AES_CTR_xcrypt_buffer implementation from aes.c. 
//  The main observation which makes this implementation possible is that 
//  CTR blocks are independent one from the other: block j = AES(IV + j).

// One counter block. A single AESENC does a full AES round (SubBytes -> ShiftRows ->
// MixColumns -> AddRoundKey), so this replaces the entire scalar Cipher().
static inline __m128i aes_encrypt_block(const __m128i* roundKey, __m128i payload)
{
    payload = _mm_xor_si128(payload, roundKey[0]);
    for (size_t round = 1; round < 10; round++) {
        payload = _mm_aesenc_si128(payload, roundKey[round]);
    }
    return _mm_aesenclast_si128(payload, roundKey[10]);
}

// Eight independent blocks in lockstep. AESENC has 4-cycle latency but 1/cycle
// throughput, so keeping 8 blocks in flight hides the latency and saturates the unit.
static inline void aes_encrypt_x8(const __m128i* roundKey, __m128i payload[8])
{
    for (size_t i = 0; i < 8; i++) {
        payload[i] = _mm_xor_si128(payload[i], roundKey[0]);
    }
    for (size_t round = 1; round < 10; round++) {
        for (size_t i = 0; i < 8; i++) {
            payload[i] = _mm_aesenc_si128(payload[i], roundKey[round]);
        }
    }
    for (size_t i = 0; i < 8; ++i) {
        payload[i] = _mm_aesenclast_si128(payload[i], roundKey[10]);
    }
}

// Due to the fact that tiny-AES' implementation uses a big-endian byte ordering for 
// IV, but x86 architecture stores data in little-endian format, we need to swap 
// the bytes of the IV (split into two blocks of 8 bytes in order to make use of 
// uint64_t and swap afterwards, storing the result within an __m128i register).
static inline __m128i ctr_block(uint64_t high, uint64_t low)
{
    return _mm_set_epi64x((long long)__builtin_bswap64(low),
                          (long long)__builtin_bswap64(high));
}

// Encrypt one contiguous slice (whole blocks; the last one may be partial).
static void ctr_xcrypt_range(const __m128i* roundKey, 
                             uint8_t* buffer, 
                             size_t byteCount,
                             uint64_t startBlock, 
                             uint64_t ivHigh, 
                             uint64_t ivLow) {
    // This slice's counter = global IV + index of its first block (as per the observation from the top of this file)
    uint64_t lo = ivLow + startBlock;
    uint64_t hi = ivHigh + (lo < ivLow ? 1 : 0);   // carry into hi if lo wrapped

    size_t offset = 0;
    // Main path: 8 blocks (128 bytes) per iteration.
    for (; offset + 8 * AES_BLOCKLEN <= byteCount; offset += 8 * AES_BLOCKLEN)
    {
        __m128i keyStream[8];
        for (size_t i = 0; i < 8; i++)
        {
            keyStream[i] = ctr_block(hi, lo);
            // 128-bit big-endian increment
            if (lo++;
                lo == 0) {
                hi++;                 
            }
        }
        aes_encrypt_x8(roundKey, keyStream);

        // Apply the keystream 32 bytes (2 blocks) at a time through the use of 256-bit registers
        for (size_t i = 0; i < 8; i += 2)
        {
            __m256i payload         = _mm256_loadu_si256(reinterpret_cast<const __m256i*>(buffer + offset + i * 16));
            __m256i keyStreamVector = _mm256_set_m128i(keyStream[i + 1], keyStream[i]);
            __m256i postXorPayload  = _mm256_xor_si256(payload, keyStreamVector); 
            _mm256_storeu_si256(reinterpret_cast<__m256i*>(buffer + offset + i * 16),
                                postXorPayload);
        }
    }
    // Remaining whole blocks which didn't fit within the 8-block chunks, alongside a possible partial final block.
    while (offset < byteCount)
    {
        __m128i keyStream = aes_encrypt_block(roundKey, ctr_block(hi, lo));
        if (lo++;
            lo == 0) {
            hi++;                 
        }
        size_t n = byteCount - offset;
        if (n >= AES_BLOCKLEN)
        {
            __m128i payload        = _mm_loadu_si128(reinterpret_cast<const __m128i*>(buffer + offset));
            __m128i postXorPayload = _mm_xor_si128(payload, keyStream);
            _mm_storeu_si128(reinterpret_cast<__m128i*>(buffer + offset), postXorPayload);
            offset += AES_BLOCKLEN;
        }
        else
        {
            uint8_t keyBytes[AES_BLOCKLEN];
            _mm_storeu_si128(reinterpret_cast<__m128i*>(keyBytes), keyStream);
            for (size_t i = 0; i < n; i++) {
                buffer[offset + i] ^= keyBytes[i];
            }
            offset += n;
        }
    }
}

// Keeping same signature as AES_CTR_xcrypt_buffer for ease of swap, but splitting the
// buffer into block-aligned slices, running the AES-NI pipeline on each one of them.
static void AES_CTR_xcrypt_buffer_fast(struct AES_ctx* ctx, 
                                       uint8_t* buf, 
                                       size_t length) {
    __m128i roundKey[11];
    for (size_t i = 0; i < 11; i++) {
        roundKey[i] = _mm_loadu_si128(reinterpret_cast<const __m128i*>(ctx->RoundKey + 16 * i));
    }

    // IV as a 128-bit big-endian counter (matches tiny-AES' implementation byte-wise increment).
    uint64_t ivHigh = 0, ivLow = 0;
    for (size_t i = 0; i < 8;  i++) {
        ivHigh = (ivHigh << 8) | ctx->Iv[i];
    }
    for (size_t i = 8; i < 16; i++) {
        ivLow = (ivLow << 8) | ctx->Iv[i];
    }

    size_t totalBlocks = (length + AES_BLOCKLEN - 1) / AES_BLOCKLEN;
    size_t nThreads = threadCount;
    if (totalBlocks < nThreads) {
        nThreads = std::max<size_t>(1, totalBlocks);
    }
    size_t blocksPerThread = (totalBlocks + nThreads - 1) / nThreads;

    // Slices are block-aligned, so threads never write the same bytes (no data dependencies
    // means no synchronization / locking required).
    std::vector<std::thread> pool;
    for (size_t t = 0; t < nThreads; ++t)
    {
        size_t startBlock = t * blocksPerThread;
        if (startBlock >= totalBlocks) break;
        size_t startByte = startBlock * AES_BLOCKLEN;
        size_t nbytes = std::min(length - startByte, blocksPerThread * AES_BLOCKLEN);
        pool.emplace_back(ctr_xcrypt_range, roundKey, buf + startByte, nbytes,
                          static_cast<uint64_t>(startBlock), ivHigh, ivLow);
    }
    for (std::thread& th : pool) {
        th.join();
    }
    // The computation is considered complete after the last thread has joined.
}

int main()
{
    // Read the whole input file into a byte buffer.
    std::ifstream inFile;
    inFile.open(kInputFile, std::ios::binary);
    if (!inFile.is_open())
    {
        std::cerr << "Could not open input file: " << kInputFile << std::endl;
        return EXIT_STATUS::UNABLE_TO_OPEN_INPUT_FILE;
    }

    // Get size of the input file (thanks CPPReference this API is atrocious)
    inFile.seekg(0, inFile.end);
    std::streamsize size = inFile.tellg();
    inFile.seekg(0, inFile.beg);

    if (size < 0)
    {
        std::cerr << "Could not determine size of: " << kInputFile << std::endl;
        inFile.close();
        return EXIT_STATUS::UNABLE_TO_GET_INPUT_SIZE;
    }

    // Buffer used for storing input file contents
    std::vector<uint8_t> buffer(static_cast<size_t>(size));
    if (size > 0) {
        if (inFile.read(reinterpret_cast<char *>(buffer.data()), buffer.size());
            (inFile.rdstate() & std::ifstream::failbit) != 0 || (inFile.rdstate() & std::ifstream::eofbit) !=0) 
        {
            std::cerr << "Could not read input file: " << kInputFile << std::endl;
            inFile.close();
            return EXIT_STATUS::UNABLE_TO_READ_INPUT_CONTENTS;
        }
    }
    
    // If this point is reached than that means that the input file contents have been successfully read
    inFile.close();

    // Encrypt in place using AES-128 CTR. No padding is needed in CTR mode (unlike CBC or ECB mode)
    struct AES_ctx ctx;
    AES_init_ctx_iv(&ctx, key, iv);
    auto startTimeStamp = std::chrono::steady_clock::now();
    AES_CTR_xcrypt_buffer_fast(&ctx, buffer.data(), buffer.size());
    auto stopTimeStamp = std::chrono::steady_clock::now();

    // Write the ciphertext (raw bytes) to the output file.
    std::ofstream outFile; 
    outFile.open(kOutputFile, std::ios::binary);
    if (!outFile.is_open())
    {
        std::cerr << "Could not open output file: " << kOutputFile << std::endl;
        return EXIT_STATUS::UNABLE_TO_OPEN_OUTPUT_FILE;
    }
    if (!buffer.empty()) {
        if (outFile.write(reinterpret_cast<char *>(buffer.data()), buffer.size());
            (outFile.rdstate() & std::ofstream::badbit) !=0)
        {
            std::cerr << "Could not write output file: " << kOutputFile << std::endl;
            outFile.close();
            return EXIT_STATUS::UNABLE_TO_WRITE_TO_OUTPUT;
        }
    }
    // If this point is reached than that means that encrypted data has been successfully written to the output file
    outFile.close();

    auto encryptionDurationMs = std::chrono::duration_cast<std::chrono::milliseconds>(stopTimeStamp - startTimeStamp).count();
    std::cout << "Encrypted " << size << " byte(s): " 
              << kInputFile << " -> " << kOutputFile 
              << std::endl;
    std::cout << "Encryption duration: " << encryptionDurationMs << " [ms]" << std::endl;
    return EXIT_STATUS::SUCCESS;
}
